name: Desktop App Robot Test
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Robot Framework tests
        run: robot tasks.robot
